package com.covielloDevs.SistemaDeVerificacion.utils.enums;

public enum TipoPreferencia {
    SUSCRIPCION_PLAN_COMMON,
    SUSCRIPCION_PLAN_PROFESSIONAL,
    SUSCRIPCION_PLAN_CORPORATE,
    COMPRA_LICENCIA_PREPAGA_CHICA,
    COMPRA_LICENCIA_PREPAGA_MEDIANA,
    COMPRA_LICENCIA_PREPAGA_GRANDE,
    COMPRA_LICENCIA_PREPAGA_MASIVA
}