spring.application.name=SistemaDeVerificacion
spring.main.lazy-initialization=true

token.secret=${JWT_SECRET}
token.expiration.hours=${JWT_EXPIRATION_HOURS}
qr.token.secret=${QR_SECRET}
qr.token.expiration.minutes=5
#BASE DE DATOS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#EMAIL
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE}
spring.mail.transport.protocol=${MAIL_TRANSPORT_PROTOCOL}
#MERCADOPAGO
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.sponsor.id=${MERCADOPAGO_SPONSOR_ID}
mercadopago.default.image.url:${DEFAULT_IMAGE_URL}
mercadopago.back.success.url=${APP_BASE_URL}/v1/mercadopago/success
mercadopago.back.pending.url=${APP_BASE_URL}/v1/mercadopago/pending
mercadopago.back.failure.url=${APP_BASE_URL}/v1/mercadopago/failure
mercadopago.auto.return=approved
mercadopago.notification.path=/v1/mercadopago/notifications

#SUPABASE
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=files