spring.application.name=SistemaDeVerificacion

server.port=8080
server.address=0.0.0.0

logging.level.org.springframework=DEBUG

token.secret=${JWT_SECRET:Mickahela18}
token.expiration.hours=${JWT_EXPIRATION_HOURS:24}

qr.token.secret=${QR_SECRET:claveQR123}
qr.token.expiration.minutes=5

# ======================
# BASE DE DATOS
# ======================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nuvix_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Mickahela}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# ======================
# ESTATICOS
# ======================
spring.web.resources.static-locations=file:/home/matias/pruebas/**
spring.mvc.static-path-pattern=/images/**,/spreadsheets/**

# ======================
# EMAIL
# ======================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:ruscittomicaela@gmail.com}
spring.mail.password=${MAIL_PASSWORD:bcfxkzzledmncrzz}

# ======================
# MERCADOPAGO
# ======================
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:APP_USR-8687690170260494-111722-12c9ce6ded4054410e7cab915889144c-2999278400}
mercadopago.sponsor.id=${MERCADOPAGO_SPONSOR_ID:2999278400}
mercadopago.notification.path=/v1/mercadopago/webhook

mercadopago.back.success.url=${APP_BASE_URL:http://localhost:8080}/v1/mercadopago/success
mercadopago.back.pending.url=${APP_BASE_URL:http://localhost:8080}/v1/mercadopago/pending
mercadopago.back.failure.url=${APP_BASE_URL:http://localhost:8080}/v1/mercadopago/failure

# ======================
# SUPABASE
# ======================
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=files

# ======================
# OTROS
# ======================
default.image.url=${DEFAULT_IMAGE_URL:http://url.com/img.jpg}